# Funding options for this project
# GitHub Sponsors: https://github.com/sponsors

# Replace with your username or organization
# github: [username]

# Custom funding links
# custom: ['https://www.paypal.me/username', 'https://ko-fi.com/username']
